listener 1883
protocol mqtt
allow_anonymous true
acl_file /mosquitto/config/acl

listener 9001
protocol websockets
allow_anonymous true
acl_file /mosquitto/config/acl

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
log_timestamp true

max_queued_messages 1000
message_size_limit 0
